// Task name
//Status -> when click you can change status (radioInput)
//Img > Img -> first img(creator task), second(assign person)
//Type -> when click you can change tags (checkbox)
//duration....
//.....
//.....
